DROP TABLE IF EXISTS account;

CREATE TABLE account
(
  USERNAME VARCHAR(100) PRIMARY KEY NOT NULL,
  PASSWORD VARCHAR(255)             NOT NULL,
  EMAIL    VARCHAR(100)             NOT NULL,
  ENABLED  TINYINT(1)               NOT NULL
);
CREATE UNIQUE INDEX EMAIL
  ON account (EMAIL);
CREATE UNIQUE INDEX USERNAME
  ON account (USERNAME);