SET FOREIGN_KEY_CHECKS = 0; -- to disable them
DROP TABLE IF EXISTS has_role;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS role;
SET FOREIGN_KEY_CHECKS = 1; -- to re-enable them

CREATE TABLE account
(
  USERNAME VARCHAR(100) PRIMARY KEY NOT NULL,
  PASSWORD VARCHAR(255)             NOT NULL,
  EMAIL    VARCHAR(100)             NOT NULL,
  ENABLED  TINYINT(1)               NOT NULL
);
CREATE UNIQUE INDEX EMAIL
  ON account (EMAIL);
CREATE UNIQUE INDEX USERNAME
  ON account (USERNAME);

CREATE TABLE role (
  ID        INT(12) PRIMARY KEY AUTO_INCREMENT        NOT NULL,
  ROLE_NAME VARCHAR(100) UNIQUE                       NOT NULL
);
CREATE UNIQUE INDEX ID
  ON role (ID);


CREATE TABLE has_role
(
  ID       INT(12) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USERNAME VARCHAR(100)                       NOT NULL,
  ROLE_ID  INT(12)                            NOT NULL,
  CONSTRAINT FK_USERNAME FOREIGN KEY (USERNAME) REFERENCES account (USERNAME),
  CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES role (ID)
);
CREATE UNIQUE INDEX USERNAME
  ON has_role (USERNAME);
CREATE UNIQUE INDEX ROLE_ID
  ON has_role (ROLE_ID);
