# noinspection SqlResolveForFile
;


INSERT INTO ACCOUNT (USERNAME, PASSWORD, EMAIL, ENABLED) VALUES ("Mister", "asdasd@emasdasdail.com", "aaaaaaaaa", TRUE);
INSERT INTO ACCOUNT (USERNAME, PASSWORD, EMAIL, ENABLED) VALUES ("Mister2", "asdasd22@emasdasdail.com", "222222", TRUE);

INSERT INTO ROLE (ID, ROLE_NAME) VALUE (1, "ADMIN");
INSERT INTO ROLE (ID, ROLE_NAME) VALUE (2, "USER");
INSERT INTO ROLE (ID, ROLE_NAME) VALUE (3, "CUSTOMER");
INSERT INTO ROLE (ID, ROLE_NAME) VALUE (4, "CONTRACTOR");
INSERT INTO ROLE (ID, ROLE_NAME) VALUE (5, "ACCOUNTANT");

INSERT INTO HAS_ROLE (USERNAME, ROLE_ID) VALUE ("Mister", 1);
INSERT INTO HAS_ROLE (USERNAME, ROLE_ID) VALUE ("Mister", 2);
INSERT INTO HAS_ROLE (USERNAME, ROLE_ID) VALUE ("Mister", 3);
INSERT INTO HAS_ROLE (USERNAME, ROLE_ID) VALUE ("Mister", 4);
INSERT INTO HAS_ROLE (USERNAME, ROLE_ID) VALUE ("Mister", 5);

INSERT INTO HAS_ROLE (USERNAME, ROLE_ID) VALUE ("Mister2", 2);
INSERT INTO HAS_ROLE (USERNAME, ROLE_ID) VALUE ("Mister2", 3);